### PR TITLE
Revert "Add ability to ignore inline with #notgitleak"

### PR DESCRIPTION
**Pull request by pshickeydev**
Reverts stolostron/secure-engineering-container#22

### CODE REVIEW

**Review by gparvin — APPROVED** [review]
I wonder if there are bug fixes needed in newer releases to make it work correctly...  Approving.

**Comment by pshickeydev** [comment]
Yeah, I'm thinking I'll need to bite the bullet and re-write our gitleaks scanning. It may be possible to change the regex for inline false positives, but that feels like a band-aid on a broken ankle.

**Comment by pshickeydev** [comment]
Issue opened for tracking: https://github.com/stolostron/backlog/issues/26031

**Pull request merged**
