### PR TITLE
change org name to stolostron

### PR DESCRIPTION
**Pull request by pshickeydev**

### CODE REVIEW

**Comment by pshickeydev** [comment]
Do not merge until credentials have been updated

**Review by arewm — APPROVED** [review]
LGTM. Prow is currently disabled, feel free to merge manually.

**Comment by pshickeydev** [comment]
Merge to main will trigger a build of the image so waiting until I've updated the credentials for the build-image.yml workflow.

**Comment by pshickeydev** [comment]
`sec` built and pushed successfully with new credentials
https://github.com/stolostron/secure-engineering-container/runs/4707246608
deleting branch

**Pull request merged**
